### 1.了解卷积神经网络的基本结构

In [5]:
import tensorflow as tf
import numpy as np

In [3]:
input=tf.random.normal([1,13,5,5]) # [ 批量数，高度，宽度，通道 ] 的4D张量表示
filter=tf.random.normal([6,3,5,2]) # [ filter高，filter宽，上一特征图数量，filter数量 ] 的4D张量表示
op1=tf.nn.conv2d(input,filter,strides=[1,5,2,1],padding='SAME')
print(op1.shape) # [ 批量数，高度，宽度，通道 ]
op2=tf.nn.conv2d(input,filter,strides=[1,5,2,1],padding='VALID')
print(op2.shape) # [ 批量数，高度，宽度，通道 ]

(1, 3, 3, 2)
(1, 2, 2, 2)


In [6]:
# 这里我们的输入图像 image 的张量形状为 [1, 7, 7, 1]
image = np.array([[
    [0, 0, 0, 0, 0, 0, 0],
    [0, 1, 0, 1, 2, 1, 0],
    [0, 0, 2, 2, 0, 1, 0],
    [0, 1, 1, 0, 2, 1, 0],
    [0, 0, 2, 1, 1, 0, 0],
    [0, 2, 1, 1, 2, 0, 0],
    [0, 0, 0, 0, 0, 0, 0]
]], dtype=np.float32)
image.shape

(1, 7, 7)

In [7]:
image = np.expand_dims(image, axis=-1)  
image.shape

(1, 7, 7, 1)

In [9]:
W = np.array([[
    [ 0, 0, -1], 
    [ 0, 1, 0 ], 
    [-2, 0, 2 ]
]], dtype=np.float32) #权重用形状为 [ fh，fw，f`n，fn ] 的4D张量表示
b = np.array([1], dtype=np.float32) #偏置项用1D张量 [ fn ] 表示
print('W.shape:',W.shape)
print('b.shape:',b.shape)

W.shape: (1, 3, 3)
b.shape: (1,)


In [10]:
#建立一个仅有一个卷积层的模型，用 W 和 b 初始化
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D
model=Sequential()
model.add(Conv2D(filters=1,
                 kernel_size=[3,3],
                 kernel_initializer=tf.constant_initializer(W),
                 bias_initializer=tf.constant_initializer(b)
                ))

output=model(image)
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (1, 5, 5, 1)              10        
Total params: 10
Trainable params: 10
Non-trainable params: 0
_________________________________________________________________


In [11]:
print(tf.squeeze(output))

tf.Tensor(
[[ 6.  5. -2.  1.  2.]
 [ 3.  0.  3.  2. -2.]
 [ 4.  2. -1.  0.  0.]
 [ 2.  1.  2. -1. -3.]
 [ 1.  1.  1.  3.  1.]], shape=(5, 5), dtype=float32)
