In [2]:
import tensorflow as tf
import tensorflow.compat.v1 as tf1
import numpy as np

### 1）生成张量

In [2]:
tf.zeros([3, 4], tf.int32)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])>

In [3]:
tf.ones([3, 5], tf.int32)

<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])>

In [4]:
tf.eye(6,dtype=tf.int32)

<tf.Tensor: shape=(6, 6), dtype=int32, numpy=
array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])>

In [5]:
tf.fill([3,3],6)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])>

In [6]:
tf.random.normal([2,4])

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[-1.8345212 , -1.2473832 , -0.01549946, -0.16367036],
       [ 2.1303735 , -0.66512847,  1.5054108 , -1.3861955 ]],
      dtype=float32)>

In [7]:
tf.random.truncated_normal([2,4])

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[ 1.468852  , -0.6286899 , -0.16098958, -1.144105  ],
       [-0.24096355, -0.16640003, -0.737144  , -0.18835442]],
      dtype=float32)>

In [8]:
tf.random.uniform([2,4])

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[0.99504066, 0.72150147, 0.3785714 , 0.36296248],
       [0.24003506, 0.202268  , 0.9825257 , 0.72039783]], dtype=float32)>

In [9]:
#随机地将张量沿其第一维度打乱
tf.random.shuffle(tf.range(10)) 

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([1, 8, 6, 2, 5, 7, 0, 4, 9, 3])>

### 2）数据类型转换

In [31]:
string='123.6'
n1=tf1.string_to_number(string)
print('n1:',n1)
a=[6.9,1.2,3.5]
n2=tf1.cast(a,tf.double)
print('n2:',n2)

n3=tf1.cast(a,tf.float32)
print('n3:',n3)

n4=tf1.cast(a,tf.int32)
print('n4:',n4)

n5=tf1.cast(a,tf.int64)
print('n5:',n5)

print('-'*30)
n6=tf1.to_double(a)
print('n6:',n6)

n1: tf.Tensor(123.6, shape=(), dtype=float32)
n2: tf.Tensor([6.9000001  1.20000005 3.5       ], shape=(3,), dtype=float64)
n3: tf.Tensor([6.9 1.2 3.5], shape=(3,), dtype=float32)
n4: tf.Tensor([6 1 3], shape=(3,), dtype=int32)
n5: tf.Tensor([6 1 3], shape=(3,), dtype=int64)
------------------------------
n6: tf.Tensor([6.9000001  1.20000005 3.5       ], shape=(3,), dtype=float64)


### 3) 形状操作

shape

In [12]:
t = [[[1, 1, 1], [2, 2, 2]], [[3, 3, 3], [4, 4, 4]]]
tf.shape(t) #返回数据的shape

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 2, 3])>

size

In [13]:
t = [[[1, 1, 1], [2, 2, 2]], [[3, 3, 3], [4, 4, 4]]]
tf.size(t) #返回数据的元素数量

<tf.Tensor: shape=(), dtype=int32, numpy=12>

rank

In [14]:
t = [[[1, 1, 1], [2, 2, 2]], [[3, 3, 3], [4, 4, 4]]]
tf.rank(t) #维度

<tf.Tensor: shape=(), dtype=int32, numpy=3>

reshape

In [15]:
t = [1, 2, 3, 4, 5, 6, 7, 8, 9]
print(tf.shape(t))

t2 = tf.reshape(t, [3, 3])
print(tf.shape(t2))

t3 = tf.reshape(t, [3, -1])
print(t3)

tf.Tensor([9], shape=(1,), dtype=int32)
tf.Tensor([3 3], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


### 4）Tensor切片操作

expand_dims

In [16]:
t = [4,3,2]
tf.shape(t)

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([3])>

In [5]:
t = [4,3,2]
t1 = tf.shape(tf.expand_dims(t, 0))
t2 = tf.shape(tf.expand_dims(t, 1))
t3 = tf.shape(tf.expand_dims(t, -1))
print(t1,'\n',t2,'\n',t3)
print('-'*30)
t4 = tf.ones([2,3,5])
t5 = tf.shape(tf.expand_dims(t4, 0))
t6 = tf.shape(tf.expand_dims(t4, 2))
t7 = tf.shape(tf.expand_dims(t4, -1))
print(t4)
print(t5,'\n',t6,'\n',t7)

tf.Tensor([1 3], shape=(2,), dtype=int32) 
 tf.Tensor([3 1], shape=(2,), dtype=int32) 
 tf.Tensor([3 1], shape=(2,), dtype=int32)
------------------------------
tf.Tensor(
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]], shape=(2, 3, 5), dtype=float32)
tf.Tensor([1 2 3 5], shape=(4,), dtype=int32) 
 tf.Tensor([2 3 1 5], shape=(4,), dtype=int32) 
 tf.Tensor([2 3 5 1], shape=(4,), dtype=int32)


slice

In [15]:
t = [[[1, 1, 1], [2, 2, 2]],[[3, 3, 3], [4, 4, 4]],[[5, 5, 5], [6, 6, 6]]]
t1 = tf.slice(t, [1, 0, 0], [1, 1, 3])
t2 = tf.slice(t, [1, 0, 0], [1, 2, 3])
t3 = tf.slice(t, [1, 0, 0], [2, 1, 3])

print(t1)
# print(t2)
# print(t3)

tf.Tensor([[[3 3 3]]], shape=(1, 1, 3), dtype=int32)


split

In [19]:
s=tf.fill([5,30],9)
s0,s1,s2=tf.split(s,3,1)
print(tf.shape(s0))
print(tf.shape(s1))
print(tf.shape(s2))

tf.Tensor([ 5 10], shape=(2,), dtype=int32)
tf.Tensor([ 5 10], shape=(2,), dtype=int32)
tf.Tensor([ 5 10], shape=(2,), dtype=int32)


In [8]:
s=tf.fill([5,30],9)
print(s)
s0,s1,s2=tf.split(s,num_or_size_splits=3,axis=1)
print(tf.shape(s0))
print(tf.shape(s1))
print(tf.shape(s2))
print(s0)

tf.Tensor(
[[9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9]], shape=(5, 30), dtype=int32)
tf.Tensor([ 5 10], shape=(2,), dtype=int32)
tf.Tensor([ 5 10], shape=(2,), dtype=int32)
tf.Tensor([ 5 10], shape=(2,), dtype=int32)
tf.Tensor(
[[9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]], shape=(5, 10), dtype=int32)


concat

In [21]:
t1 = [[1, 2, 3], [4, 5, 6]]
t2 = [[7, 8, 9], [10, 11, 12]]
t3 = tf.concat([t1, t2], 0) 
t4 = tf.concat([t1, t2], 1) 
print(t3)
print(t4)

tf.Tensor(
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]], shape=(4, 3), dtype=int32)
tf.Tensor(
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]], shape=(2, 6), dtype=int32)


In [11]:
t1 = [[1, 2, 3], [4, 5, 6]]
t2 = [[7, 8, 9], [10, 11, 12]]
t3 = tf.concat([t1, t2], 0)
print(t3)

tf.Tensor(
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]], shape=(4, 3), dtype=int32)


stack

In [13]:
x = [1, 4]
y = [2, 5]
z = [3, 6]
t1 =tf.stack([x, y, z])
print(t1)
#沿着第一维stack
t2 = tf.stack([x, y, z], axis=1)
print(t2)

#等价于
# t3 = np.asarray([x, y, z])
# print(t3)

tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


reverse

In [23]:
t = [[[[ 0,  1,  2,  3],
[ 4,  5,  6,  7],
[ 8,  9, 10, 11]],
[[12, 13, 14, 15],
[16, 17, 18, 19],
[20, 21, 22, 23]]]]
# tensor 't' shape is [1, 2, 3, 4]

dims = [3]  # or 'dims = [-1]''
t1 = tf.reverse(t, dims)
print(t1)

dims = [1] #or 'dims = [-3]'
t2 = tf.reverse(t, dims)

dims = [2] #or 'dims = [-2]'
t3 = tf.reverse(t, dims)
print(t1)
print(t2)
print(t3)

tf.Tensor(
[[[[ 3  2  1  0]
   [ 7  6  5  4]
   [11 10  9  8]]

  [[15 14 13 12]
   [19 18 17 16]
   [23 22 21 20]]]], shape=(1, 2, 3, 4), dtype=int32)
tf.Tensor(
[[[[ 3  2  1  0]
   [ 7  6  5  4]
   [11 10  9  8]]

  [[15 14 13 12]
   [19 18 17 16]
   [23 22 21 20]]]], shape=(1, 2, 3, 4), dtype=int32)
tf.Tensor(
[[[[12 13 14 15]
   [16 17 18 19]
   [20 21 22 23]]

  [[ 0  1  2  3]
   [ 4  5  6  7]
   [ 8  9 10 11]]]], shape=(1, 2, 3, 4), dtype=int32)
tf.Tensor(
[[[[ 8  9 10 11]
   [ 4  5  6  7]
   [ 0  1  2  3]]

  [[20 21 22 23]
   [16 17 18 19]
   [12 13 14 15]]]], shape=(1, 2, 3, 4), dtype=int32)


transpose

In [24]:
t = [[1, 2, 3],[4, 5, 6]]
t1 = tf.transpose(t) 
t2 = tf.transpose(t, perm=[1, 0])
print(t1)
print(t2)

tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)


one_hot

In [25]:
indices = [0, 1, 2]
depth = 3
t1 = tf.one_hot(indices, depth)  

indices = [0, 2, -1, 1]
depth = 3
t2 = tf.one_hot(indices, depth,on_value=5.0, off_value=0.0,axis=-1)  
indices = [[0, 2], [1, -1]]
t3 = tf.one_hot(indices, depth,on_value=1.0, off_value=0.0,axis=-1)  

print(t1)
print(t2)
print(t3)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[5. 0. 0.]
 [0. 0. 5.]
 [0. 0. 0.]
 [0. 5. 0.]], shape=(4, 3), dtype=float32)
tf.Tensor(
[[[1. 0. 0.]
  [0. 0. 1.]]

 [[0. 1. 0.]
  [0. 0. 0.]]], shape=(2, 2, 3), dtype=float32)


unique

In [26]:
t = [1, 1, 2, 4, 4, 4, 7, 8, 8]
y, idx = tf.unique(t)
print(y)
print(idx)

tf.Tensor([1 2 4 7 8], shape=(5,), dtype=int32)
tf.Tensor([0 0 1 2 2 2 3 4 4], shape=(9,), dtype=int32)


### 5）矩阵操作

matmul

In [27]:
a = tf.constant([1, 2, 3, 4, 5, 6], shape=[2, 3])
b = tf.constant([7, 8, 9, 10, 11, 12], shape=[3, 2])
c = tf.matmul(a, b)

diag对角矩阵

In [28]:
diagonal = [1, 2, 3, 4]
tf.linalg.diag(diagonal) 

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])>

det求方阵行列式

In [54]:

import tensorflow as tf

# 定义一个2x2的矩阵
matrix = tf.constant([[1.0, 2.0], [3.0, 4.0]])

# 计算矩阵的行列式
tf.linalg.det(matrix)

<tf.Tensor: shape=(), dtype=float32, numpy=-2.0>

In [56]:
#tf.linalg.inv(x)的例子
matrix = tf.constant([[1.0, 2.0], [3.0, 4.0]])
tf.linalg.inv(matrix)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-2.0000002 ,  1.0000001 ],
       [ 1.5000001 , -0.50000006]], dtype=float32)>

In [59]:
#tf.linalg.trace(x)的例子
matrix = tf.constant([[1.0, 3.0], [3.0, 4.0]])
tf.linalg.trace(matrix)

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

### 6) 复数操作

In [32]:
real=[1.1, 2.2]
imag=[3.3, 4.4]
tf.complex(real, imag)

<tf.Tensor: shape=(2,), dtype=complex64, numpy=array([1.1+3.3j, 2.2+4.4j], dtype=complex64)>

In [33]:
x=tf.complex(real, imag)
tf.abs(x)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([3.4785054, 4.9193497], dtype=float32)>

In [34]:
tf.math.conj(x)

<tf.Tensor: shape=(2,), dtype=complex64, numpy=array([1.1-3.3j, 2.2-4.4j], dtype=complex64)>

In [35]:
tf.math.imag(x)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([3.3, 4.4], dtype=float32)>

In [36]:
tf.math.real(x)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.1, 2.2], dtype=float32)>

### 练习1

#### 1）读取数据并查看数据结构 下载pima-indians-diabetes.csv文件并在python中加载

In [3]:
import tensorflow as tf
import numpy as np
import pandas as pd

# 加载数据
data = pd.read_csv("pima-indians-diabetes.csv",header=None,delimiter=",")
data

0         1         2         3         4         5         6  \
0    0.639947  0.866045 -0.031990  0.670643 -0.181541  0.166619  0.468492   
1   -0.844885 -1.205066 -0.528319 -0.012301 -0.181541 -0.852200 -0.365061   
2    1.233880  2.016662 -0.693761 -0.012301 -0.181541 -1.332500  0.604397   
3   -0.844885 -1.073567 -0.528319 -0.695245 -0.540642 -0.633881 -0.920763   
4   -1.141852  0.504422 -2.679076  0.670643  0.316566  1.549303  5.484909   
..        ...       ...       ...       ...       ...       ...       ...   
763  1.827813 -0.679069  0.298896  2.150354  0.455573  0.064737 -0.908682   
764 -0.547919  0.011301 -0.197433 -0.239949 -0.181541  0.632365 -0.398282   
765  0.342981 -0.021574 -0.031990 -0.695245 -0.332132 -0.910418 -0.685193   
766 -0.844885  0.142800 -1.024647 -0.012301 -0.181541 -0.342790 -0.371101   
767 -0.844885 -0.942068 -0.197433  0.215347 -0.181541 -0.299127 -0.473785   

            7  8  
0    1.425995  1  
1   -0.190672  0  
2   -0.105584  1  
3   -1.041549  0  
4   -0.020496  1  
..        ... ..  
763  2.532136  0  
764 -0.531023  0  
765 -0.275760  0  
766  1.170732  1  
767 -0.871374  0  

[768 rows x 9 columns]

In [4]:
X=data.iloc[:,0:8]
y=data[8]
X

0         1         2         3         4         5         6  \
0    0.639947  0.866045 -0.031990  0.670643 -0.181541  0.166619  0.468492   
1   -0.844885 -1.205066 -0.528319 -0.012301 -0.181541 -0.852200 -0.365061   
2    1.233880  2.016662 -0.693761 -0.012301 -0.181541 -1.332500  0.604397   
3   -0.844885 -1.073567 -0.528319 -0.695245 -0.540642 -0.633881 -0.920763   
4   -1.141852  0.504422 -2.679076  0.670643  0.316566  1.549303  5.484909   
..        ...       ...       ...       ...       ...       ...       ...   
763  1.827813 -0.679069  0.298896  2.150354  0.455573  0.064737 -0.908682   
764 -0.547919  0.011301 -0.197433 -0.239949 -0.181541  0.632365 -0.398282   
765  0.342981 -0.021574 -0.031990 -0.695245 -0.332132 -0.910418 -0.685193   
766 -0.844885  0.142800 -1.024647 -0.012301 -0.181541 -0.342790 -0.371101   
767 -0.844885 -0.942068 -0.197433  0.215347 -0.181541 -0.299127 -0.473785   

            7  
0    1.425995  
1   -0.190672  
2   -0.105584  
3   -1.041549  
4   -0.020496  
..        ...  
763  2.532136  
764 -0.531023  
765 -0.275760  
766  1.170732  
767 -0.871374  

[768 rows x 8 columns]

### 2）设计神经网络并训练模型

In [2]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten,Dense, Dropout

In [40]:
'''模型'''
model=Sequential([
    Dense(12,input_dim=8,activation='relu'), #全连接
    Dense(1, activation='sigmoid') #输出层
])

'''编译'''
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

'''训练'''
model.fit(X,y,epochs=100,batch_size=10)

'''评估'''
loss, accuracy = model.evaluate(X, y)
print("\nLoss: %.2f, Accuracy: %.2f%%" % (loss, accuracy*100))

'''预测'''
pred = model.predict(X)
predictions = [float(np.round(x)) for x in pred]
accuracy = np.mean(predictions == y)
print("Prediction Accuracy: %.2f%%" % (accuracy*100))
# Loss: 0.40, Accuracy: 81.64%
# Prediction Accuracy: 81.64%

Epoch 1/100
77/77 [==============================] - 0s 471us/step - loss: 0.7714 - accuracy: 0.4232
Epoch 2/100
77/77 [==============================] - 0s 445us/step - loss: 0.6274 - accuracy: 0.6615
Epoch 3/100
77/77 [==============================] - 0s 392us/step - loss: 0.5522 - accuracy: 0.7344
Epoch 4/100
77/77 [==============================] - 0s 389us/step - loss: 0.5127 - accuracy: 0.7474
Epoch 5/100
77/77 [==============================] - 0s 303us/step - loss: 0.4903 - accuracy: 0.7448
Epoch 6/100
77/77 [==============================] - 0s 258us/step - loss: 0.4763 - accuracy: 0.7539
Epoch 7/100
77/77 [==============================] - 0s 394us/step - loss: 0.4677 - accuracy: 0.7591
Epoch 8/100
77/77 [==============================] - 0s 300us/step - loss: 0.4615 - accuracy: 0.7656
Epoch 9/100
77/77 [==============================] - 0s 395us/step - loss: 0.4568 - accuracy: 0.7682
Epoch 10/100
77/77 [==============================] - 0s 408us/step - loss: 0.4533 - accura

In [41]:
# # 加载数据
# dataset = numpy.loadtxt("pima-indians-diabetes.csv", delimiter=",")
# X = dataset[:,0:8]
# Y = dataset[:,8]

# # step 1. define the network
# model = tf.keras.Sequential()
# model.add(tf.keras.layers.Dense(12, input_dim=8, activation='relu'))
# model.add(tf.keras.layers.Dense(1, activation='sigmoid'))
# # step 2. compile the network
# model.compile(loss='binary_crossentropy', optimizer='adam', 
#               metrics=['accuracy'])
# # step 3. fit the network
# history = model.fit(X, Y, epochs=100, batch_size=10)
# # step 4. evaluate the network
# loss, accuracy = model.evaluate(X, Y)
# print("\nLoss: %.2f, Accuracy: %.2f%%" % (loss, accuracy*100))
# # step 5. make predictions
# probabilities = model.predict(X)
# predictions = [float(numpy.round(x)) for x in probabilities]
# accuracy = numpy.mean(predictions == Y)
# print("Prediction Accuracy: %.2f%%" % (accuracy*100))

### 3）保存和加载模型 TensorFlow有两种保存模型的方法，一种是只保存模型的权重和偏置，另一种是保存整个模型

（1）保存模型的权重和偏置

In [42]:
'''保存模型的权重和偏置'''
model.save_weights('./save_weights/my_save_weights')

In [43]:
'''恢复权重'''
model.load_weights('./save_weights/my_save_weights')

（2）保存整个模型

In [44]:
'''保存整个模型'''
model.save('my_model.h5')
restored_model = tf.keras.models.load_model('my_model.h5')

In [11]:
restored_model = tf.keras.models.load_model('my_model.h5')
loss, accuracy = restored_model.evaluate(X, y)
print("\nLoss: %.2f, Accuracy: %.2f%%" % (loss, accuracy*100))

24/24 [==============================] - 0s 1ms/step - loss: 0.4045 - accuracy: 0.7969

Loss: 0.40, Accuracy: 79.69%


### 完成MNIST数据读取、模型搭建、训练、测试等过程，并尝试修改模型以提高测试效果

In [1]:
import tensorflow as tf
import numpy as np

def load_data(path):
    with np.load(path) as f:
        x_train, y_train = f['x_train'], f['y_train']
        x_test, y_test = f['x_test'], f['y_test']
        return (x_train, y_train), (x_test, y_test)

((trainX, trainY), (testX, testY)) = load_data("mnist.npz")
trainX = trainX.astype("float32") / 255.0
testX = testX.astype("float32") / 255.0

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])
model.fit(trainX, trainY, epochs=5)
model.evaluate(testX,  testY, verbose=2)
model.summary()

Epoch 1/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2938 - accuracy: 0.9149
Epoch 2/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1397 - accuracy: 0.9583
Epoch 3/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1066 - accuracy: 0.9674
Epoch 4/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0858 - accuracy: 0.9740
Epoch 5/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0741 - accuracy: 0.9767
313/313 - 1s - loss: 0.0707 - accuracy: 0.9769
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten (Flatten)            (None, 784)               0         
_________________________________________________________________
dense (Dense)                (None, 128)               100480    
_________________________________________________________________
dropout (Dropout)            (No

In [46]:
test_loss, test_acc = model.evaluate(testX,testY,verbose=2) #损失值和准确率
print('\nTest accuracy:', test_acc)
print('\nTest loss:', test_loss)

313/313 - 0s - loss: 0.0791 - accuracy: 0.9759

Test accuracy: 0.9758999943733215

Test loss: 0.07912839949131012


In [47]:
from tensorflow.keras.datasets import mnist

(x_train,y_train),(x_test,y_test)=mnist.load_data()
#np.unique(y_train) #[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
'''将像素值除以255是为了将图像的灰度值范围从0到255转换到0到1之间的范围'''
x_train, x_test = x_train / 255.0, x_test / 255.0

'''模型'''
model=Sequential([
    Flatten(input_shape=(28,28)), #展平
    Dense(128, activation='relu'), #全连接
    Dropout(0.2), #防止过拟合
    Dense(10, activation='softmax') #输出层，激活函数为softmax，用于输出分类结果
])

'''编译'''
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

'''回调函数记录训练信息'''
log_dir="logs/fit/mnist"
callback=tf.keras.callbacks.TensorBoard(
    log_dir=log_dir,
    histogram_freq=1
)

'''训练'''
model.fit(x_train,y_train,
          epochs=500,callbacks=[callback])

'''评估'''
model.evaluate(x_test,y_test,verbose=2)

Epoch 1/500
1875/1875 [==============================] - 2s 979us/step - loss: 0.2905 - accuracy: 0.9157
Epoch 2/500
1875/1875 [==============================] - 2s 818us/step - loss: 0.1412 - accuracy: 0.9575
Epoch 3/500
1875/1875 [==============================] - 1s 755us/step - loss: 0.1074 - accuracy: 0.9670
Epoch 4/500
1875/1875 [==============================] - 1s 741us/step - loss: 0.0849 - accuracy: 0.9740
Epoch 5/500
1875/1875 [==============================] - 1s 734us/step - loss: 0.0731 - accuracy: 0.9775
Epoch 6/500
1875/1875 [==============================] - 1s 747us/step - loss: 0.0651 - accuracy: 0.9799
Epoch 7/500
1875/1875 [==============================] - 1s 688us/step - loss: 0.0596 - accuracy: 0.9811
Epoch 8/500
1875/1875 [==============================] - 1s 699us/step - loss: 0.0520 - accuracy: 0.9829
Epoch 9/500
1875/1875 [==============================] - 1s 698us/step - loss: 0.0475 - accuracy: 0.9845
Epoch 10/500
1875/1875 [==============================]

KeyboardInterrupt: 

In [ ]:
from tensorflow.keras.datasets import mnist
from tensorflow.keras.layers import Layer,Dense,Conv2D,AvgPool2D,Flatten,MaxPool2D,Dropout,concatenate,Input,Softmax,BatchNormalization,Activation,GlobalAveragePooling2D,ReLU
from tensorflow.keras.utils import to_categorical

(X_train,y_train),(X_test,y_test)=mnist.load_data()

X_train4D=X_train.reshape(X_train.shape[0],28,28,1).astype('float32')
X_test4D = X_test.reshape(X_test.shape[0], 28, 28, 1).astype('float32')

#归一化
X_train4D_Normalize = X_train4D / 255 # 归一化
X_test4D_Normalize = X_test4D / 255

#将类别向量映射为二值类别矩阵,将原有的类别向量转换为独热编码的形式
y_trainOnehot=to_categorical(y_train)
y_testOnehot = to_categorical(y_test)

#建立模型
model = Sequential()

#一层卷积
model.add(Conv2D(filters=6,
                          kernel_size=(5,5),
                          strides=1,
                          input_shape=[28,28,1],
                          activation='relu'
                ))
#池化
model.add(AvgPool2D(pool_size=(2,2)))
#二层卷积
model.add(Conv2D(filters=16,
                          kernel_size=(5,5),
                          strides=1,
                          activation='relu'
                ))
#池化
model.add(AvgPool2D(pool_size=(2,2)))

#全连接层
#将多维输入一维化，即展平操作。这是从卷积层到全连接层的过渡
model.add(Flatten())
model.add(Dense(120,activation='relu'))
model.add(Dense(84,activation='relu'))
model.add(Dense(10,activation='softmax'))

model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_2 (Conv2D)            (None, 24, 24, 6)         156       
_________________________________________________________________
average_pooling2d (AveragePo (None, 12, 12, 6)         0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 8, 8, 16)          2416      
_________________________________________________________________
average_pooling2d_1 (Average (None, 4, 4, 16)          0         
_________________________________________________________________
flatten_2 (Flatten)          (None, 256)               0         
_________________________________________________________________
dense_6 (Dense)              (None, 120)               30840     
_________________________________________________________________
dense_7 (Dense)              (None, 84)               

In [ ]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])
history=model.fit(x=X_train4D_Normalize,y=y_trainOnehot,epochs=10,validation_split=0.2)

Epoch 1/10
1500/1500 [==============================] - 7s 5ms/step - loss: 0.2645 - accuracy: 0.9191 - val_loss: 0.1117 - val_accuracy: 0.9657
Epoch 2/10
1500/1500 [==============================] - 7s 5ms/step - loss: 0.0885 - accuracy: 0.9731 - val_loss: 0.0846 - val_accuracy: 0.9758
Epoch 3/10
1500/1500 [==============================] - 8s 5ms/step - loss: 0.0636 - accuracy: 0.9796 - val_loss: 0.0698 - val_accuracy: 0.9793
Epoch 4/10
1500/1500 [==============================] - 8s 5ms/step - loss: 0.0491 - accuracy: 0.9845 - val_loss: 0.0555 - val_accuracy: 0.9826
Epoch 5/10
1500/1500 [==============================] - 8s 5ms/step - loss: 0.0409 - accuracy: 0.9867 - val_loss: 0.0507 - val_accuracy: 0.9847
Epoch 6/10
1500/1500 [==============================] - 14s 9ms/step - loss: 0.0321 - accuracy: 0.9893 - val_loss: 0.0478 - val_accuracy: 0.9870
Epoch 7/10
1500/1500 [==============================] - 15s 10ms/step - loss: 0.0279 - accuracy: 0.9910 - val_loss: 0.0448 - val_accura

In [ ]:
'''评估'''
test_loss, test_acc = model.evaluate(X_test4D_Normalize,y_testOnehot,verbose=2) #损失值和准确率
print('\nTest accuracy:', test_acc)
print('\nTest loss:', test_loss)

313/313 - 2s - loss: 0.0406 - accuracy: 0.9882

Test accuracy: 0.9882000088691711

Test loss: 0.04063167795538902
