In [1]:
from gym import envs
import gym
import numpy as np
print(envs.registry.all())

dict_values([EnvSpec(Copy-v0), EnvSpec(RepeatCopy-v0), EnvSpec(ReversedAddition-v0), EnvSpec(ReversedAddition3-v0), EnvSpec(DuplicatedInput-v0), EnvSpec(Reverse-v0), EnvSpec(CartPole-v0), EnvSpec(CartPole-v1), EnvSpec(MountainCar-v0), EnvSpec(MountainCarContinuous-v0), EnvSpec(Pendulum-v0), EnvSpec(Acrobot-v1), EnvSpec(LunarLander-v2), EnvSpec(LunarLanderContinuous-v2), EnvSpec(BipedalWalker-v3), EnvSpec(BipedalWalkerHardcore-v3), EnvSpec(CarRacing-v0), EnvSpec(Blackjack-v0), EnvSpec(KellyCoinflip-v0), EnvSpec(KellyCoinflipGeneralized-v0), EnvSpec(FrozenLake-v1), EnvSpec(FrozenLake8x8-v1), EnvSpec(CliffWalking-v0), EnvSpec(NChain-v0), EnvSpec(Roulette-v0), EnvSpec(Taxi-v3), EnvSpec(GuessingGame-v0), EnvSpec(HotterColder-v0), EnvSpec(Reacher-v2), EnvSpec(Pusher-v2), EnvSpec(Thrower-v2), EnvSpec(Striker-v2), EnvSpec(InvertedPendulum-v2), EnvSpec(InvertedDoublePendulum-v2), EnvSpec(HalfCheetah-v2), EnvSpec(HalfCheetah-v3), EnvSpec(Hopper-v2), EnvSpec(Hopper-v3), EnvSpec(Swimmer-v2), EnvSp

### GYM数值空间

In [2]:
env=gym.make("CartPole-v0")

#查看动作空间
print(env.action_space)

#随机选取动作
env.action_space.sample()

Discrete(2)


0

### 查看环境空间

In [3]:
print(env.observation_space)

#查看环境空间取值范围
print(env.observation_space.high)
print(env.observation_space.low)

Box([-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38], [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38], (4,), float32)
[4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38]


### CartPole环境
* 每个观测是包含四个浮点的 1D Numpy 向量
    * 小车的水平位置（0 为中心）
    * 小车的速度
    * 杆的角度（垂直）
    * 杆的角速度

In [4]:
#1.创建环境
env = gym.make('CartPole-v0')
#2.初始化环境，返回观察值
obs = env.reset()
obs

array([ 0.00284395, -0.01242044, -0.01232633,  0.00926808])

In [5]:
#3.CartPole动作定义 0: 向左推小车 1: 向右推小车
next_state, reward, done, info = env.step(0)
print("next_state: ",next_state)
print("reward: ",reward)
print("done: ",done)
print("info: ",info)

next_state:  [ 0.00259554 -0.20736347 -0.01214097  0.29803656]
reward:  1.0
done:  False
info:  {}


### CartPole-v0示例

In [6]:
"""
使用随机策略来控制杆子的移动
运行20次
每个 episode 中执行，最多执行100步
"""
env = gym.make('CartPole-v0')
for i_episode in range(20): # 外层循环
    obs = env.reset()
    for t in range(100): # 内层循环
        # 内层循环体
        env.render()
        action = env.action_space.sample()
        obs, re, done, info = env.step(action)
        print(obs)
        if done:
            print("done == True : %d" % (t+1))
            break
env.close()

[ 0.03064465 -0.21867458  0.04810884  0.2716269 ]
[ 0.02627116 -0.02427095  0.05354138 -0.00550261]
[ 0.02578574  0.17004389  0.05343132 -0.28082354]
[ 0.02918662 -0.02579791  0.04781485  0.02822126]
[ 0.02867066 -0.22157179  0.04837928  0.33559866]
[ 0.02423922 -0.41734767  0.05509125  0.64313684]
[ 0.01589227 -0.61319245  0.06795399  0.95264695]
[ 0.00362842 -0.80915973  0.08700693  1.26588254]
[-0.01255477 -1.00527898  0.11232458  1.5844964 ]
[-0.03266035 -1.20154334  0.14401451  1.90999175]
[-0.05669122 -1.00823887  0.18221434  1.66523078]
[-0.076856   -1.20495371  0.21551896  2.00869315]
done == True : 12
[-0.04492946 -0.20181254  0.02572306  0.27735695]
[-0.04896571 -0.39729184  0.0312702   0.57804065]
[-0.05691154 -0.59283778  0.04283101  0.88040811]
[-0.0687683  -0.78851461  0.06043918  1.18624264]
[-0.08453859 -0.59422628  0.08416403  0.91310057]
[-0.09642312 -0.40033755  0.10242604  0.64801195]
[-0.10442987 -0.59672607  0.11538628  0.97111147]
[-0.11636439 -0.79319171  0.1348

### GYM实现随机运动策略

In [7]:
import gym
env=gym.make("CartPole-v0")
env.reset()
for _ in range(1000):
    env.render()
    env.step(env.action_space.sample())
env.close()

c:\Program Files\Python36\lib\site-packages\gym\logger.py:34: UserWarning: WARN: You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.
  warnings.warn(colorize("%s: %s" % ("WARN", msg % args), "yellow"))


### GYM实现简单策略
当杆向左倾斜时加速左移，当杆向右倾斜时加速右移。我们使用这个策略来获得超过 500 步的平均回报。

In [8]:
def basic_policy(obs):    
    angle = obs[2]    
    return 0 if angle < 0 else 1

totals = [ ] 
for episode in range(500):    
    episode_rewards = 0    
    obs = env.reset()    
    for step in range(1000): 
        action = basic_policy(obs)        
        obs, reward, done, info = env.step(action)        
        episode_rewards += reward        
        if done:            
            break    
    totals.append(episode_rewards)

print(episode_rewards)
np.mean(totals), np.std(totals), np.min(totals), np.max(totals)

47.0


(42.8, 8.499647051495726, 25.0, 72.0)

### 马尔可夫链

In [12]:
transition_probabilities=[
    [0.7,0.2,0.0,0.1],
    [0.0,0.0,0.9,0.1],
    [0.0,1.0,0.0,0.0],
    [0.0,0.0,0.0,1.0]
]
n_max_steps=50

def print_sequence(start_state=0):
    current_state = start_state
    print("States:", end=" ")
    for step in range(n_max_steps):
        print(current_state, end=" ")
        current_state = np.random.choice(range(4), p=transition_probabilities[current_state])
    else:
        print("...", end="")
    print()

for _ in range(10):
    print_sequence()

States: 0 0 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 ...
States: 0 0 0 0 0 0 1 2 1 2 1 2 1 2 1 2 1 2 1 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 ...
States: 0 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 ...
States: 0 0 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 ...
States: 0 0 0 1 2 1 2 1 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 ...
States: 0 0 0 0 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 ...
States: 0 0 0 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 ...
States: 0 0 0 1 2 1 2 1 2 1 2 1 2 1 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 ...
States: 0 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 

### Q值迭代算法

In [13]:
nan = np.nan #无法到达
T = np.array([ # shape=[s, a, s']
    [[0.7, 0.3, 0.0], [1.0, 0.0, 0.0], [0.8, 0.2, 0.0]],
    [[0.0, 1.0, 0.0], [nan, nan, nan], [0.0, 0.0, 1.0]],
    [[nan, nan, nan], [0.8, 0.1, 0.1], [nan, nan, nan]],
])

R = np.array([ # shape=[s, a, s']
    [[10., 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0,  0.0]],
    [[0.0, 0.0, 0.0], [nan, nan, nan], [0.0, 0.0, -50.]],
    [[nan, nan, nan], [40., 0.0, 0.0], [nan, nan,  nan]],
])

possible_actions = [[0, 1, 2], [0, 2], [1]]#shape = [s,a]

In [14]:
#初始化变量
Q = np.full((3, 3), -np.inf) # -inf 表示不可能的动作
for state, actions in enumerate(possible_actions):
    Q[state, actions] = 0.0 # 所有动作的初始值都为0.0

d_rate = 0.95
n_iterations = 100

In [15]:
#运行Q-Value 迭代算法
for iteration in range(n_iterations):
    Q_prev = Q.copy()
    for s in range(3):
        for a in possible_actions[s]:
            Q[s, a] = np.sum([T[s,a, sp]*(R[s,a,sp]+d_rate*np.max(Q_prev[sp])) for sp in range(3) ])
Q

array([[21.88646117, 20.79149867, 16.854807  ],
       [ 1.10804034,        -inf,  1.16703135],
       [       -inf, 53.8607061 ,        -inf]])

### Q-Learning

In [17]:
import numpy.random as rnd
learning_rate0 = 0.05
learning_rate_decay = 0.1
discount_rate = 0.9
n_iterations = 20000

s = 0 # start in state 0
Q = np.full((3, 3), -np.inf) # -inf为不可能动作

for state, actions in enumerate(possible_actions):
    Q[state, actions] = 0.0 

In [19]:
for iteration in range(n_iterations):
    # 随机选择一个动作
    a = rnd.choice(possible_actions[s]) 
    # 使用T[s, a] 选择下一个状态
    sp = rnd.choice(range(3), p=T[s, a])     
    reward = R[s, a, sp]
    learning_rate = learning_rate0 / (1 + iteration * learning_rate_decay)
    Q[s, a] = learning_rate * Q[s, a] + (1 - learning_rate) * (
        reward + discount_rate * np.max(Q[sp])
    )
    s = sp # 移动到下一个状态
Q

array([[ 21.44239994,  53.52441579,  49.47192337],
       [ 23.82482265,         -inf, -28.55490023],
       [        -inf,  88.17036621,         -inf]])

### gym倒立摆

In [1]:
import gym
env = gym.make('CartPole-v0')
env.reset()

for _ in range(1000):
    env.render()
    env.step(env.action_space.sample()) # take a random action

env.close()

c:\Program Files\Python36\lib\site-packages\gym\logger.py:34: UserWarning: WARN: You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.
  warnings.warn(colorize("%s: %s" % ("WARN", msg % args), "yellow"))


### gym弹球

In [2]:
import gym
import time
env = gym.make("Breakout-v0")
obs = env.reset()
#弹球的动作空间为4，即有4个动作，0,1,2,3.
#这四个值分别控制球拍的四个动作，0：原地不动，1：发球，2：右移，3：左移
#任务：打开一个命令提示符界面，通过手动执行env.step(n);env.render()等命令，实现手动控制球拍得到5分。
import gym

# Create the Breakout environment
env = gym.make("Breakout-v0")

# Reset the environment
obs = env.reset()

# Manually control the paddle to achieve a score of 5
score = 0
while score < 5:
    # Render the environment
    env.render()
    
    # Get user input for paddle movement
    action = int(input("Enter action (0: Stay, 1: Serve, 2: Move Right, 3: Move Left): "))
    
    # Perform the action in the environment
    obs, reward, done, info = env.step(action)
    
    # Update the score
    score += reward
    
    # Print the current score
    print("Score:", score)
    
# Close the environment
env.close()

Score: 0.0
Score: 0.0
Score: 0.0
Score: 0.0
Score: 0.0
Score: 0.0
Score: 0.0
Score: 0.0
Score: 0.0


IndexError: index 32 is out of bounds for axis 0 with size 4

: 